name: nameless_ai
description: A program to chat with AI models.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  provider: ^6.0.5

  go_router: ^16.2.1

  hive: ^2.0.4
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1

  dio: ^5.4.0

  flutter_markdown: ^0.6.20+1
  url_launcher: ^6.2.2
  markdown: ^7.1.1
  flutter_math_fork: ^0.7.4

  dynamic_color: ^1.1.5

  flutter_svg: ^2.0.10

  intl: 0.20.2
  uuid: ^4.3.1
  path_provider: ^2.1.2
  chinese_font_library: ^1.2.0
  package_info_plus: 8.3.1
  file_picker: ^10.3.2
  share_plus: 11.1.0
  flutter_highlight: ^0.7.0
  highlight: ^0.7.0

  photo_view: ^0.15.0
  gal: ^2.3.2
  introduction_screen: ^4.0.0

  tiktoken: ^1.0.1
  flutter_local_notifications: ^19.4.1
  local_auth: ^2.3.0
  fl_chart: ^1.1.0
  screenshot: ^3.0.0
  flutter_colorpicker: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.8

flutter:
  uses-material-design: true

  generate: true

  assets:
    - assets/icon/

